name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Please (manifest)
        uses: google-github-actions/release-please-action@v4
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}


